title: Liyuan Li # your name (or website title) here
logo: "/images/IMG-9465 (1).JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst
  <br><br>
  Highly experienced business analyst adept at collecting, analyzing, and visualizing large dataset, developing ML models, and delivering business insights. 
  <br><br>
  <a href="https://www.linkedin.com/in/liyuan-li/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
