title: John Doe # your name (or website title) here
logo: "/images/IMG-9465 (1).JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst
  <br><br>
  Highly experienced business analyst adept at collecting, analyzing, and visualizing large dataset, developing models, and delivering business insights. /
  Processing an extensive analytic skill, project management & problem-solving skills; knowledge in Statistic, Machine Learning & Finance (CFA); a significant ability to work in cross-functional teams. 
  <br><br>
  <a href="https://www.linkedin.com/in/liyuan-li/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
